[package]
name = "cielo-rs-interface"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
reqwest = "0.12.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
tokio = {version = "1.39.2", features =["full"]}
